name: Librarian
favicon: null
layout_spectrum: 0.2841975905466825
typography_spectrum: 0.5659921537153423
title: Librarian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.15594421792775393
  lightness: 0.2496555030811578
  saturation: 0.532025930006057
  rhythmicContrast: 0.6935637863352895
purpose: []
